---
- name: Remove DNS record
  route53:
    state: absent
    zone: "{{ route53_zone }}"
    record: "{{ route53_record }}"
    ttl: "{{ route53_record_ttl }}"
    type: "{{ route53_record_type }}"
    value: "{{ route53_record_value }}"
    private_zone: "{{ route53_private_zone | default ('no') }} "
    wait: "{{ route53_wait }}"
    wait_timeout: "{{ route53_wait_timeout }}"